# Piraeus Operator values for the piraeus-operator chart

installCRDs: true

nodeSelector:
  storage.k8s.io/satellite: "yes"

tolerations:
  - key: drbd.linbit.com/lost-quorum
    effect: NoSchedule
  - key: drbd.linbit.com/force-io-error
    effect: NoSchedule
  - key: linstor-storage
    operator: Equal
    value: "true"
    effect: NoSchedule

operator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
