---
# Operator builds and loads the kernel module on the node
# Set to false if the AMI has the driver preinstalled
driver:
  enabled: true
  # https://catalog.ngc.nvidia.com/orgs/nvidia/containers/driver/tags
  version: "580.126.20"
  repository: nvcr.io/nvidia
  image: driver
  # Compiles driver on the node from kernel-devel
  usePrecompiled: false

# Patches containerd config and installs nvidia-container-runtime on the node.
# Set to false if the AMI already has the toolkit
toolkit:
  enabled: true

# Propagate toleration to all DaemonSets
# Required because the Karpenter `gpu` NodePool taints with nvidia.com/gpu=true:NoSchedule
daemonsets:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule

# GPU partitioning
mig:
  strategy: none
migManager:
  enabled: false
vgpuManager:
  enabled: false
vgpuDeviceManager:
  enabled: false
sandboxWorkloads:
  enabled: false

dcgmExporter:
  enabled: true

# Adds GPU-specific node labels
gfd:
  enabled: true

# Bundled NFD
nfd:
  enabled: true

# Operator controller
operator:
  replicas: 1
