apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-llm
  namespace: jupyterlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 100Gi
