---
replicas: 1

resources:
  limits:
    memory: 256Mi
    cpu: 500m
  requests:
    memory: 64Mi
    cpu: 50m

nodeSelector:
  karpenter.sh/controller: "true"
tolerations:
  - key: karpenter.sh/controller
    operator: Exists
    effect: NoSchedule

prometheus:
  monitor:
    enabled: false
