---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alb-controller
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            enable_alb_controller: "true"
  template:
    metadata:
      name: alb-controller
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      sources:
        - repoURL: https://aws.github.io/eks-charts
          chart: aws-load-balancer-controller
          targetRevision: 3.4.2
          helm:
            # explicit: install chart CRDs
            skipCrds: false
            valueFiles:
              - $values/argocd/helm-values/alb-controller/values.yaml
            values: |
              clusterName: "{{ index .metadata.annotations "cluster_name" }}"
              region: "{{ index .metadata.annotations "region" }}"
              vpcId: "{{ index .metadata.annotations "vpc_id" }}"
        - repoURL: https://github.com/silazare/mlops-infra-example
          targetRevision: '{{ index .metadata.annotations "target_revision" }}'
          ref: values
      destination:
        server: "{{ .server }}"
        namespace: kube-system
      # The chart generates a self-signed webhook cert via `genSelfSignedCert` every Helm render
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          jqPathExpressions:
            - .webhooks[]?.clientConfig.caBundle
        - group: ""
          kind: Secret
          name: aws-load-balancer-tls
          jsonPointers:
            - /data
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
