---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alloy
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: alloy
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: alloy
          targetRevision: 1.8.0
          helm:
            releaseName: alloy
            valueFiles:
              - $values/argocd/helm-values/alloy/values.yaml
        - repoURL: https://github.com/silazare/mlops-infra-example
          targetRevision: "{{metadata.annotations.target_revision}}"
          ref: values
      destination:
        server: "{{server}}"
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
