---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            enable_cert_manager: "true"
  template:
    metadata:
      name: cert-manager
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      sources:
        - repoURL: https://charts.jetstack.io
          chart: cert-manager
          targetRevision: v1.20.2
          helm:
            valueFiles:
              - $values/argocd/helm-values/cert-manager/values.yaml
        - repoURL: https://github.com/silazare/mlops-infra-example
          targetRevision: "{{metadata.annotations.target_revision}}"
          ref: values
      destination:
        server: "{{server}}"
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
