---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istiod
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            enable_istio: "true"
  template:
    metadata:
      name: istiod
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      sources:
        - repoURL: https://istio-release.storage.googleapis.com/charts
          chart: istiod
          targetRevision: 1.30.1
          helm:
            valueFiles:
              - $values/argocd/helm-values/istiod/values.yaml
        - repoURL: https://github.com/silazare/mlops-infra-example
          targetRevision: "{{metadata.annotations.target_revision}}"
          ref: values
      destination:
        server: "{{server}}"
        namespace: istio-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
      ignoreDifferences:
        # istiod self-injects caBundle into its webhooks at runtime
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          jqPathExpressions:
            - '.webhooks[].clientConfig.caBundle'
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          jqPathExpressions:
            - '.webhooks[].clientConfig.caBundle'
