---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: linstor-cluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: linstor-cluster
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: ghcr.io/piraeusdatastore/helm-charts
          chart: linstor-cluster
          targetRevision: 1.1.1
          helm:
            releaseName: linstor-cluster
            valueFiles:
              - $values/argocd/helm-values/linstor-cluster/values.yaml
        - repoURL: https://github.com/silazare/mlops-infra-example
          targetRevision: "{{metadata.annotations.target_revision}}"
          ref: values
      destination:
        server: "{{server}}"
        namespace: piraeus-datastore
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 2m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
