---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mimir
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: mimir
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: mimir-distributed
          targetRevision: 6.0.6
          helm:
            releaseName: mimir
            valueFiles:
              - $values/argocd/helm-values/mimir/values.yaml
            # S3 buckets + region are from the cluster Secret annotations
            values: |
              mimir:
                structuredConfig:
                  common:
                    storage:
                      s3:
                        endpoint: s3.{{metadata.annotations.region}}.amazonaws.com
                        region: {{metadata.annotations.region}}
                  blocks_storage:
                    s3:
                      bucket_name: {{metadata.annotations.mimir_blocks_bucket}}
                  alertmanager_storage:
                    s3:
                      bucket_name: {{metadata.annotations.mimir_alertmanager_bucket}}
                  ruler_storage:
                    s3:
                      bucket_name: {{metadata.annotations.mimir_ruler_bucket}}
        - repoURL: https://github.com/silazare/mlops-infra-example
          targetRevision: "{{metadata.annotations.target_revision}}"
          ref: values
      destination:
        server: "{{server}}"
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
