---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: piraeus-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            enable_linstor: "true"
  template:
    metadata:
      name: piraeus-operator
      annotations:
        # CRDs from this chart must be installed before linstor-cluster
        argocd.argoproj.io/sync-wave: "0"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: ghcr.io/piraeusdatastore/piraeus-operator
          chart: piraeus
          targetRevision: 2.10.7
          helm:
            releaseName: piraeus-operator
            valueFiles:
              - $values/argocd/helm-values/piraeus-operator/values.yaml
        - repoURL: https://github.com/silazare/mlops-infra-example
          targetRevision: '{{ index .metadata.annotations "target_revision" }}'
          ref: values
      destination:
        server: "{{ .server }}"
        namespace: piraeus-datastore
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: piraeus-operator-tls
          namespace: piraeus-datastore
          jsonPointers:
            - /data
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: piraeus-operator-validating-webhook-configuration
          jqPathExpressions:
            - .webhooks[].clientConfig.caBundle
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
