---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: traefik
    spec:
      project: default
      sources:
        - repoURL: https://traefik.github.io/charts
          chart: traefik
          targetRevision: 39.0.8
          helm:
            valueFiles:
              - $values/argocd/helm-values/traefik/values.yaml
            values: |
              service:
                annotations:
                  service.beta.kubernetes.io/aws-load-balancer-security-groups: "{{metadata.annotations.traefik_sg_id}}"
        - repoURL: https://github.com/silazare/mlops-infra-example
          targetRevision: "{{metadata.annotations.target_revision}}"
          ref: values
      destination:
        server: "{{server}}"
        namespace: traefik
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
