---
# Traefik: default IngressClass behind the NLB (ALB controller), routes Ingress/IngressRoute to services
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            enable_traefik: "true"
  template:
    metadata:
      name: traefik
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: default
      sources:
        - repoURL: https://traefik.github.io/charts
          chart: traefik
          targetRevision: 41.5.0
          helm:
            releaseName: traefik
            skipCrds: false
            valueFiles:
              - $values/argocd/helm-values/traefik/values.yaml
            values: |
              service:
                annotations:
                  service.beta.kubernetes.io/aws-load-balancer-security-groups: "{{ index .metadata.annotations "traefik_sg_id" }}"
        - repoURL: https://github.com/silazare/mlops-infra-example
          targetRevision: '{{ index .metadata.annotations "target_revision" }}'
          ref: values
      destination:
        server: "{{ .server }}"
        namespace: traefik
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - CreateNamespace=true
        retry:
          limit: 10
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
