{{- include "llm-d-modelserver.validate" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.resourceName }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-d-modelserver.labels" . | nindent 4 }}
automountServiceAccountToken: false
